name: Run Python mock unit test

on:
  push:
    branches: [ main ]
  pull_request:

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip3 install -r ./terraform/python/requirements.txt
          echo
      - name: Run Tests
        run: |
          cd $GITHUB_WORKSPACE/terraform/python/tests/
          python3 -m unittest -v tests.py
